#pragma once
namespace RBX {

	namespace Text
	{
		enum Font {
			FONT_LEGACY = 0, FONT_ARIAL = 1, FONT_ARIALBOLD = 2,
			FONT_SOURCESANS = 3, FONT_SOURCESANSBOLD = 4,
			FONT_SOURCESANSLIGHT = 5, FONT_SOURCESANSITALIC = 6,
			FONT_BODONI = 7, FONT_GARAMOND = 8, FONT_CARTOON = 9,
			FONT_CODE = 10, FONT_HIGHWAY = 11, FONT_SCIFI = 12,
			FONT_ARCADE = 13, FONT_FANTASY = 14, FONT_ANTIQUE = 15,
			FONT_SOURCESANSSEMIBOLD = 16, FONT_GOTHAM = 17,
			FONT_GOTHAMMEDIUM = 18, FONT_GOTHAMBOLD = 19,
			FONT_GOTHAMBLACK = 20, FONT_AMATICSC = 21,
			FONT_BANGERS = 22, FONT_CREEPSTER = 23, FONT_DENKONE = 24,
			FONT_FONDAMENTO = 25, FONT_FREDOKAONE = 26,
			FONT_GRENZEGOTISCH = 27, FONT_INDIEFLOWER = 28,
			FONT_JOSEFINSANS = 29, FONT_JURA = 30, FONT_KALAM = 31,
			FONT_LUCKIESTGUY = 32, FONT_MERRIWEATHER = 33,
			FONT_MICHROMA = 34, FONT_NUNITO = 35, FONT_OSWALD = 36,
			FONT_PATRICKHAND = 37, FONT_PERMANENTMARKER = 38,
			FONT_ROBOTO = 39, FONT_ROBOTOCONDENSED = 40,
			FONT_ROBOTOMONO = 41, FONT_SARPANCH = 42,
			FONT_SPECIALELITE = 43, FONT_TITILLIUMWEB = 44,
			FONT_UBUNTU = 45, FONT_BUILDERSANS = 46,
			FONT_BUILDERSANS_MEDIUM = 47, FONT_BUILDERSANS_BOLD = 48,
			FONT_BUILDERSANS_EXTRABOLD = 49, FONT_ARIMO = 50,
			FONT_ARIMOBOLD = 51, FONT_UNKNOWN = 100,
			FONT_BUILDER_ICONS_REGULAR = 101,
			FONT_BUILDER_ICONS_FILLED = 102, FONT_LAST = 103
		};

		inline bool isValidFont(Font font)
		{
			return (font >= FONT_LEGACY && font <= FONT_ARIMOBOLD) ||
				font == FONT_UNKNOWN || font == FONT_BUILDER_ICONS_REGULAR ||
				font == FONT_BUILDER_ICONS_FILLED;
		}
		// Font drawing params - copied from G3D
		enum XAlign {XALIGN_RIGHT, XALIGN_LEFT, XALIGN_CENTER};

		enum YAlign {YALIGN_TOP, /*YALIGN_BASELINE,*/ YALIGN_CENTER, YALIGN_BOTTOM};


	}
}
