source 'http://rubygems.org'

gem 'rspec'
gem 'cucumber'
gem 'random_data'
gem 'appium_lib'
gem 'pry'
gem 'rake'
gem 'yard-cucumber'
gem 'parallel_tests'
gem 'teamcity_formatter'
gem 'require_all'
gem 'simplecov'
gem 'simplecov-rcov'
gem 'cuke_sniffer'

gem "rubocop", ">= 0.49.0", require: false
