#pragma once

namespace RBX {
namespace Enums {

enum TextDirection
{
    TEXT_DIRECTION_AUTO = 0,
    TEXT_DIRECTION_LEFT_TO_RIGHT = 1,
    TEXT_DIRECTION_RIGHT_TO_LEFT = 2
};

enum HapticEffectType
{
    HAPTIC_EFFECT_CUSTOM = 0,
    HAPTIC_EFFECT_UI_HOVER = 1,
    HAPTIC_EFFECT_UI_CLICK = 2,
    HAPTIC_EFFECT_UI_NOTIFICATION = 3,
    HAPTIC_EFFECT_GAMEPLAY_EXPLOSION = 4,
    HAPTIC_EFFECT_GAMEPLAY_COLLISION = 5
};

enum ElasticBehavior
{
    ELASTIC_BEHAVIOR_WHEN_SCROLLABLE = 0,
    ELASTIC_BEHAVIOR_ALWAYS = 1,
    ELASTIC_BEHAVIOR_NEVER = 2
};

enum BorderMode
{
    BORDER_MODE_OUTLINE = 0,
    BORDER_MODE_MIDDLE = 1,
    BORDER_MODE_INSET = 2
};

enum ScrollingDirection
{
    SCROLLING_DIRECTION_X = 1,
    SCROLLING_DIRECTION_Y = 2,
    SCROLLING_DIRECTION_XY = 4
};

enum ScrollBarInset
{
    SCROLL_BAR_INSET_NONE = 0,
    SCROLL_BAR_INSET_SCROLL_BAR = 1,
    SCROLL_BAR_INSET_ALWAYS = 2
};

enum VerticalScrollBarPosition
{
    VERTICAL_SCROLL_BAR_POSITION_RIGHT = 0,
    VERTICAL_SCROLL_BAR_POSITION_LEFT = 1
};

enum VoiceChatDistanceAttenuationType
{
    VOICE_DISTANCE_INVERSE = 0,
    VOICE_DISTANCE_LEGACY = 1
};

enum RolloutState
{
    ROLLOUT_DEFAULT = 0,
    ROLLOUT_DISABLED = 1,
    ROLLOUT_ENABLED = 2
};

enum AudioApiRollout
{
    AUDIO_API_DISABLED = 0,
    AUDIO_API_AUTOMATIC = 1,
    AUDIO_API_ENABLED = 2
};

enum VoiceClientLeaveReasons
{
    VOICE_LEAVE_UNKNOWN = 0,
    VOICE_LEAVE_CLIENT_NETWORK_DISCONNECTED = 1,
    VOICE_LEAVE_PLAYER_LEFT = 2,
    VOICE_LEAVE_CLIENT_SHUTDOWN = 3,
    VOICE_LEAVE_PUBLISH_FAILED = 4,
    VOICE_LEAVE_REJOIN_RECEIVED = 5,
    VOICE_LEAVE_REBOOT = 6,
    VOICE_LEAVE_IMGUI_DEBUG = 7,
    VOICE_LEAVE_LUA_INITIATED = 8
};

enum TextInputType
{
    TEXT_INPUT_DEFAULT = 0,
    TEXT_INPUT_NO_SUGGESTIONS = 1,
    TEXT_INPUT_NUMBER = 2,
    TEXT_INPUT_EMAIL = 3,
    TEXT_INPUT_PHONE = 4,
    TEXT_INPUT_PASSWORD = 5,
    TEXT_INPUT_PASSWORD_SHOWN = 6,
    TEXT_INPUT_USERNAME = 7,
    TEXT_INPUT_ONE_TIME_PASSWORD = 8,
    TEXT_INPUT_NEW_PASSWORD = 9,
    TEXT_INPUT_NEW_PASSWORD_SHOWN = 10
};

enum ChatRestrictionStatus
{
    CHAT_RESTRICTION_UNKNOWN = 0,
    CHAT_RESTRICTION_NOT_RESTRICTED = 1,
    CHAT_RESTRICTION_RESTRICTED = 2
};

enum ReturnKeyType
{
    RETURN_KEY_DEFAULT = 0,
    RETURN_KEY_DONE = 1,
    RETURN_KEY_GO = 2,
    RETURN_KEY_NEXT = 3,
    RETURN_KEY_SEARCH = 4,
    RETURN_KEY_SEND = 5
};

enum AppShellActionType
{
    APP_SHELL_ACTION_NONE = 0,
    APP_SHELL_ACTION_OPEN_APP = 1,
    APP_SHELL_ACTION_TAP_CHAT_TAB = 2,
    APP_SHELL_ACTION_TAP_CONVERSATION_ENTRY = 3,
    APP_SHELL_ACTION_TAP_AVATAR_TAB = 4,
    APP_SHELL_ACTION_READ_CONVERSATION = 5,
    APP_SHELL_ACTION_TAP_GAME_PAGE_TAB = 6,
    APP_SHELL_ACTION_TAP_HOME_PAGE_TAB = 7,
    APP_SHELL_ACTION_GAME_PAGE_LOADED = 8,
    APP_SHELL_ACTION_HOME_PAGE_LOADED = 9,
    APP_SHELL_ACTION_AVATAR_EDITOR_PAGE_LOADED = 10,
    APP_SHELL_ACTION_HOME_PAGE_INTERACTIVE = 11
};

enum AppShellFeature
{
    APP_SHELL_FEATURE_NONE = 0,
    APP_SHELL_FEATURE_CHAT = 1,
    APP_SHELL_FEATURE_AVATAR_EDITOR = 2,
    APP_SHELL_FEATURE_GAME_PAGE = 3,
    APP_SHELL_FEATURE_HOME_PAGE = 4,
    APP_SHELL_FEATURE_MORE = 5,
    APP_SHELL_FEATURE_LANDING = 6,
    APP_SHELL_FEATURE_WATCH_PAGE = 7
};

enum ConnectionState
{
    CONNECTION_CONNECTED = 0,
    CONNECTION_DISCONNECTED = 1
};

enum AvatarChatServiceFeature
{
    AVATAR_CHAT_NONE = 0,
    AVATAR_CHAT_UNIVERSE_AUDIO = 1,
    AVATAR_CHAT_UNIVERSE_VIDEO = 2,
    AVATAR_CHAT_PLACE_AUDIO = 4,
    AVATAR_CHAT_PLACE_VIDEO = 8,
    AVATAR_CHAT_USER_AUDIO_ELIGIBLE = 16,
    AVATAR_CHAT_USER_AUDIO = 32,
    AVATAR_CHAT_USER_VIDEO_ELIGIBLE = 64,
    AVATAR_CHAT_USER_VIDEO = 128,
    AVATAR_CHAT_USER_BANNED = 256,
    AVATAR_CHAT_USER_VERIFIED_FOR_VOICE = 512
};

enum DeviceFeatureType
{
    DEVICE_FEATURE_CAPTURE = 0,
    DEVICE_FEATURE_IN_EXPERIENCE_FAE = 1
};

enum DeviceLevel
{
    DEVICE_LEVEL_LOW = 0,
    DEVICE_LEVEL_MEDIUM = 1,
    DEVICE_LEVEL_HIGH = 2
};

enum PeoplePageLayout
{
    PEOPLE_PAGE_LAYOUT_CARD = 0,
    PEOPLE_PAGE_LAYOUT_LIST = 1
};

enum AppLifecycleManagerState
{
    APP_LIFECYCLE_DETACHED = 0,
    APP_LIFECYCLE_ACTIVE = 1,
    APP_LIFECYCLE_INACTIVE = 2,
    APP_LIFECYCLE_HIDDEN = 3
};

enum CaptureType
{
    CAPTURE_TYPE_SCREENSHOT = 1,
    CAPTURE_TYPE_VIDEO = 2
};

enum CaptureGalleryPermission
{
    CAPTURE_GALLERY_READ_AND_UPLOAD = 0
};

enum ReadCapturesFromGalleryResult
{
    READ_CAPTURES_SUCCESS = 0,
    READ_CAPTURES_NEED_PERMISSION = 1
};

enum VideoCaptureStartedResult
{
    VIDEO_CAPTURE_STARTED_SUCCESS = 0,
    VIDEO_CAPTURE_STARTED_OTHER_ERROR = 1,
    VIDEO_CAPTURE_STARTED_ALREADY = 2,
    VIDEO_CAPTURE_STARTED_NO_DEVICE_SUPPORT = 3,
    VIDEO_CAPTURE_STARTED_NO_SPACE = 4
};

enum VideoCaptureResult
{
    VIDEO_CAPTURE_SUCCESS = 0,
    VIDEO_CAPTURE_OTHER_ERROR = 1,
    VIDEO_CAPTURE_SCREEN_SIZE_CHANGED = 2,
    VIDEO_CAPTURE_TIME_LIMIT_REACHED = 3
};

enum AssetType
{
    ASSET_IMAGE = 1, ASSET_TSHIRT = 2, ASSET_AUDIO = 3, ASSET_MESH = 4,
    ASSET_LUA = 5, ASSET_HAT = 8, ASSET_PLACE = 9, ASSET_MODEL = 10,
    ASSET_SHIRT = 11, ASSET_PANTS = 12, ASSET_DECAL = 13, ASSET_HEAD = 17,
    ASSET_FACE = 18, ASSET_GEAR = 19, ASSET_BADGE = 21, ASSET_ANIMATION = 24,
    ASSET_TORSO = 27, ASSET_RIGHT_ARM = 28, ASSET_LEFT_ARM = 29,
    ASSET_LEFT_LEG = 30, ASSET_RIGHT_LEG = 31, ASSET_PACKAGE = 32,
    ASSET_GAME_PASS = 34, ASSET_PLUGIN = 38, ASSET_MESH_PART = 40,
    ASSET_HAIR_ACCESSORY = 41, ASSET_FACE_ACCESSORY = 42,
    ASSET_NECK_ACCESSORY = 43, ASSET_SHOULDER_ACCESSORY = 44,
    ASSET_FRONT_ACCESSORY = 45, ASSET_BACK_ACCESSORY = 46,
    ASSET_WAIST_ACCESSORY = 47, ASSET_CLIMB_ANIMATION = 48,
    ASSET_DEATH_ANIMATION = 49, ASSET_FALL_ANIMATION = 50,
    ASSET_IDLE_ANIMATION = 51, ASSET_JUMP_ANIMATION = 52,
    ASSET_RUN_ANIMATION = 53, ASSET_SWIM_ANIMATION = 54,
    ASSET_WALK_ANIMATION = 55, ASSET_POSE_ANIMATION = 56,
    ASSET_EAR_ACCESSORY = 57, ASSET_EYE_ACCESSORY = 58,
    ASSET_EMOTE_ANIMATION = 61, ASSET_VIDEO = 62,
    ASSET_TSHIRT_ACCESSORY = 64, ASSET_SHIRT_ACCESSORY = 65,
    ASSET_PANTS_ACCESSORY = 66, ASSET_JACKET_ACCESSORY = 67,
    ASSET_SWEATER_ACCESSORY = 68, ASSET_SHORTS_ACCESSORY = 69,
    ASSET_LEFT_SHOE_ACCESSORY = 70, ASSET_RIGHT_SHOE_ACCESSORY = 71,
    ASSET_DRESS_SKIRT_ACCESSORY = 72, ASSET_FONT_FAMILY = 73,
    ASSET_EYEBROW_ACCESSORY = 76, ASSET_EYELASH_ACCESSORY = 77,
    ASSET_MOOD_ANIMATION = 78, ASSET_DYNAMIC_HEAD = 79,
    ASSET_FACE_MAKEUP = 88, ASSET_LIP_MAKEUP = 89,
    ASSET_EYE_MAKEUP = 90, ASSET_VOXEL_FRAGMENT = 91,
    ASSET_AVATAR_BACKGROUND = 92, ASSET_TEXT_DOCUMENT = 93
};

enum AccessoryType
{
    ACCESSORY_UNKNOWN = 0, ACCESSORY_HAT = 1, ACCESSORY_HAIR = 2,
    ACCESSORY_FACE = 3, ACCESSORY_NECK = 4, ACCESSORY_SHOULDER = 5,
    ACCESSORY_FRONT = 6, ACCESSORY_BACK = 7, ACCESSORY_WAIST = 8,
    ACCESSORY_TSHIRT = 9, ACCESSORY_SHIRT = 10, ACCESSORY_PANTS = 11,
    ACCESSORY_JACKET = 12, ACCESSORY_SWEATER = 13, ACCESSORY_SHORTS = 14,
    ACCESSORY_LEFT_SHOE = 15, ACCESSORY_RIGHT_SHOE = 16,
    ACCESSORY_DRESS_SKIRT = 17, ACCESSORY_EYEBROW = 18,
    ACCESSORY_EYELASH = 19
};

enum BundleType
{
    BUNDLE_BODY_PARTS = 1,
    BUNDLE_ANIMATIONS = 2,
    BUNDLE_SHOES = 3,
    BUNDLE_DYNAMIC_HEAD = 4,
    BUNDLE_DYNAMIC_HEAD_AVATAR = 5
};

enum AvatarContextMenuOption
{
    AVATAR_CONTEXT_FRIEND = 0,
    AVATAR_CONTEXT_CHAT = 1,
    AVATAR_CONTEXT_EMOTE = 2,
    AVATAR_CONTEXT_INSPECT_MENU = 3
};

enum AvatarItemType
{
    AVATAR_ITEM_ASSET = 1,
    AVATAR_ITEM_BUNDLE = 2
};

enum ContextActionResult
{
    CONTEXT_ACTION_SINK = 0,
    CONTEXT_ACTION_PASS = 1
};

enum DisplaySize
{
    DISPLAY_SIZE_SMALL = 0,
    DISPLAY_SIZE_MEDIUM = 1,
    DISPLAY_SIZE_LARGE = 2
};

enum HttpRequestType
{
    HTTP_REQUEST_DEFAULT = 0,
    HTTP_REQUEST_MARKETPLACE_SERVICE = 2,
    HTTP_REQUEST_PLAYERS = 7,
    HTTP_REQUEST_CHAT = 15,
    HTTP_REQUEST_AVATAR = 16,
    HTTP_REQUEST_ANALYTICS = 23,
    HTTP_REQUEST_LOCALIZATION = 25
};

enum AvatarAssetType
{
    AVATAR_ASSET_TSHIRT = 2, AVATAR_ASSET_HAT = 8, AVATAR_ASSET_SHIRT = 11,
    AVATAR_ASSET_PANTS = 12, AVATAR_ASSET_HEAD = 17, AVATAR_ASSET_FACE = 18,
    AVATAR_ASSET_GEAR = 19, AVATAR_ASSET_TORSO = 27, AVATAR_ASSET_RIGHT_ARM = 28,
    AVATAR_ASSET_LEFT_ARM = 29, AVATAR_ASSET_LEFT_LEG = 30, AVATAR_ASSET_RIGHT_LEG = 31,
    AVATAR_ASSET_HAIR_ACCESSORY = 41, AVATAR_ASSET_FACE_ACCESSORY = 42,
    AVATAR_ASSET_NECK_ACCESSORY = 43, AVATAR_ASSET_SHOULDER_ACCESSORY = 44,
    AVATAR_ASSET_FRONT_ACCESSORY = 45, AVATAR_ASSET_BACK_ACCESSORY = 46,
    AVATAR_ASSET_WAIST_ACCESSORY = 47, AVATAR_ASSET_CLIMB_ANIMATION = 48,
    AVATAR_ASSET_FALL_ANIMATION = 50, AVATAR_ASSET_IDLE_ANIMATION = 51,
    AVATAR_ASSET_JUMP_ANIMATION = 52, AVATAR_ASSET_RUN_ANIMATION = 53,
    AVATAR_ASSET_SWIM_ANIMATION = 54, AVATAR_ASSET_WALK_ANIMATION = 55,
    AVATAR_ASSET_EMOTE_ANIMATION = 61, AVATAR_ASSET_TSHIRT_ACCESSORY = 64,
    AVATAR_ASSET_SHIRT_ACCESSORY = 65, AVATAR_ASSET_PANTS_ACCESSORY = 66,
    AVATAR_ASSET_JACKET_ACCESSORY = 67, AVATAR_ASSET_SWEATER_ACCESSORY = 68,
    AVATAR_ASSET_SHORTS_ACCESSORY = 69, AVATAR_ASSET_LEFT_SHOE_ACCESSORY = 70,
    AVATAR_ASSET_RIGHT_SHOE_ACCESSORY = 71, AVATAR_ASSET_DRESS_SKIRT_ACCESSORY = 72,
    AVATAR_ASSET_EYEBROW_ACCESSORY = 76, AVATAR_ASSET_EYELASH_ACCESSORY = 77,
    AVATAR_ASSET_MOOD_ANIMATION = 78, AVATAR_ASSET_DYNAMIC_HEAD = 79,
    AVATAR_ASSET_FACE_MAKEUP = 88, AVATAR_ASSET_LIP_MAKEUP = 89,
    AVATAR_ASSET_EYE_MAKEUP = 90, AVATAR_ASSET_AVATAR_BACKGROUND = 92
};

enum TrackerMode { TRACKER_MODE_NONE = 0, TRACKER_MODE_AUDIO = 1, TRACKER_MODE_VIDEO = 2, TRACKER_MODE_AUDIO_VIDEO = 3 };
enum TrackerError { TRACKER_ERROR_OK = 0, TRACKER_ERROR_NO_SERVICE = 1, TRACKER_ERROR_INIT_FAILED = 2, TRACKER_ERROR_NO_VIDEO = 3, TRACKER_ERROR_VIDEO = 4, TRACKER_ERROR_VIDEO_NO_PERMISSION = 5, TRACKER_ERROR_VIDEO_UNSUPPORTED = 6, TRACKER_ERROR_NO_AUDIO = 7, TRACKER_ERROR_AUDIO = 8, TRACKER_ERROR_AUDIO_NO_PERMISSION = 9, TRACKER_ERROR_UNSUPPORTED_DEVICE = 10 };
enum TrackerFaceTrackingStatus { TRACKER_FACE_SUCCESS = 0, TRACKER_FACE_NO_FACE_FOUND = 1, TRACKER_FACE_UNKNOWN = 2, TRACKER_FACE_LOST = 3, TRACKER_FACE_HAS_TRACKING_ERROR = 4, TRACKER_FACE_OCCLUDED = 5, TRACKER_FACE_UNINITIALIZED = 6 };
enum TrackerPromptEvent { TRACKER_PROMPT_LOD_CAMERA_RECOMMEND_DISABLE = 0 };
enum TrackerExtrapolationFlagMode { TRACKER_EXTRAPOLATION_FORCE_DISABLED = 0, TRACKER_EXTRAPOLATION_FACS_AND_POSE = 1, TRACKER_EXTRAPOLATION_FACS_ONLY = 2, TRACKER_EXTRAPOLATION_AUTO = 3 };
enum TrackerLodFlagMode { TRACKER_LOD_FLAG_FORCE_FALSE = 0, TRACKER_LOD_FLAG_FORCE_TRUE = 1, TRACKER_LOD_FLAG_AUTO = 2 };
enum TrackerLodValueMode { TRACKER_LOD_VALUE_FORCE_0 = 0, TRACKER_LOD_VALUE_FORCE_1 = 1, TRACKER_LOD_VALUE_AUTO = 2 };
enum HttpError { HTTP_ERROR_OK = 0, HTTP_ERROR_INVALID_URL = 1, HTTP_ERROR_DNS_RESOLVE = 2, HTTP_ERROR_CONNECT_FAIL = 3, HTTP_ERROR_OUT_OF_MEMORY = 4, HTTP_ERROR_TIMED_OUT = 5, HTTP_ERROR_TOO_MANY_REDIRECTS = 6, HTTP_ERROR_INVALID_REDIRECT = 7, HTTP_ERROR_NET_FAIL = 8, HTTP_ERROR_ABORTED = 9, HTTP_ERROR_SSL_CONNECT_FAIL = 10, HTTP_ERROR_SSL_VERIFICATION_FAIL = 11, HTTP_ERROR_UNKNOWN = 12, HTTP_ERROR_CONNECTION_CLOSED = 13, HTTP_ERROR_SERVER_PROTOCOL = 14, HTTP_ERROR_CREATOR_ENVIRONMENTS_UNSUPPORTED = 15, HTTP_ERROR_INACTIVITY_TIMEOUT = 16, HTTP_ERROR_TOO_MANY_OUTSTANDING_REQUESTS = 17, HTTP_ERROR_INVALID_RANGE_RESPONSE = 18 };

enum ExperienceAuthScope { EXPERIENCE_AUTH_SCOPE_DEFAULT = 0, EXPERIENCE_AUTH_SCOPE_CREATOR_ASSETS_CREATE = 1 };
enum ScopeCheckResult { SCOPE_CHECK_CONSENT_ACCEPTED = 0, SCOPE_CHECK_INVALID_SCOPES = 1, SCOPE_CHECK_TIMEOUT = 2, SCOPE_CHECK_NO_USER_INPUT = 3, SCOPE_CHECK_BACKEND_ERROR = 4, SCOPE_CHECK_UNEXPECTED_ERROR = 5, SCOPE_CHECK_INVALID_ARGUMENT = 6, SCOPE_CHECK_CONSENT_DENIED = 7 };

enum MakeupType {
    MAKEUP_TYPE_FACE = 0,
    MAKEUP_TYPE_LIP = 1,
    MAKEUP_TYPE_EYE = 2
};

enum MarketplaceItemPurchaseStatus {
    MARKETPLACE_ITEM_PURCHASE_SUCCESS = 1,
    MARKETPLACE_ITEM_PURCHASE_SYSTEM_ERROR = 2,
    MARKETPLACE_ITEM_PURCHASE_ALREADY_OWNED = 3,
    MARKETPLACE_ITEM_PURCHASE_INSUFFICIENT_ROBUX = 4,
    MARKETPLACE_ITEM_PURCHASE_QUANTITY_LIMIT_EXCEEDED = 5,
    MARKETPLACE_ITEM_PURCHASE_QUOTA_EXCEEDED = 6,
    MARKETPLACE_ITEM_PURCHASE_NOT_FOR_SALE = 7,
    MARKETPLACE_ITEM_PURCHASE_NOT_AVAILABLE_FOR_PURCHASER = 8,
    MARKETPLACE_ITEM_PURCHASE_PRICE_MISMATCH = 9,
    MARKETPLACE_ITEM_PURCHASE_SOLD_OUT = 10,
    MARKETPLACE_ITEM_PURCHASE_PURCHASER_IS_SELLER = 11,
    MARKETPLACE_ITEM_PURCHASE_INSUFFICIENT_MEMBERSHIP = 12,
    MARKETPLACE_ITEM_PURCHASE_PLACE_INVALID = 13
};

enum RaycastFilterType {
    RAYCAST_FILTER_EXCLUDE = 0,
    RAYCAST_FILTER_INCLUDE = 1
};

enum PromptPublishAssetResult {
    PROMPT_PUBLISH_ASSET_SUCCESS = 1,
    PROMPT_PUBLISH_ASSET_PERMISSION_DENIED = 2,
    PROMPT_PUBLISH_ASSET_TIMEOUT = 3,
    PROMPT_PUBLISH_ASSET_UPLOAD_FAILED = 4,
    PROMPT_PUBLISH_ASSET_NO_USER_INPUT = 5,
    PROMPT_PUBLISH_ASSET_UNKNOWN_FAILURE = 6
};

enum MarketplaceBulkPurchasePromptStatus {
    MARKETPLACE_BULK_PURCHASE_COMPLETED = 1,
    MARKETPLACE_BULK_PURCHASE_ABORTED = 2,
    MARKETPLACE_BULK_PURCHASE_ERROR = 3
};

} // namespace Enums
} // namespace RBX
