include_directories("${CMAKE_SOURCE_DIR}/engine/core/include")
include_directories("${CMAKE_SOURCE_DIR}/Log/include")
if(ANDROID)
  include_directories("${CMAKE_SOURCE_DIR}/engine/core/include/rbx/Android")
endif(ANDROID)
