if(NOT DEFINED INPUT_ROOT OR NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "INPUT_ROOT and OUTPUT_FILE are required")
endif()

file(GLOB_RECURSE assets RELATIVE "${INPUT_ROOT}" "${INPUT_ROOT}/*")
list(SORT assets)
get_filename_component(output_directory "${OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${output_directory}")
file(WRITE "${OUTPUT_FILE}" "{\n  \"schemaVersion\": 1,\n  \"assets\": [\n")
set(first TRUE)
foreach(asset IN LISTS assets)
    if(IS_DIRECTORY "${INPUT_ROOT}/${asset}")
        continue()
    endif()
    file(SHA256 "${INPUT_ROOT}/${asset}" digest)
    file(SIZE "${INPUT_ROOT}/${asset}" size)
    get_filename_component(extension "${asset}" LAST_EXT)
    string(SUBSTRING "${extension}" 1 -1 type)
    string(REPLACE "\\" "/" logical_path "${asset}")
    if(NOT first)
        file(APPEND "${OUTPUT_FILE}" ",\n")
    endif()
    set(first FALSE)
    file(APPEND "${OUTPUT_FILE}"
        "    { \"logicalPath\": \"rbxasset://${logical_path}\", \"sourceCorpus\": \"legacy-source-content\", \"sha256\": \"${digest}\", \"size\": ${size}, \"type\": \"${type}\", \"licenseDecision\": \"existing-source-tree-review-required\", \"compatibility\": \"legacy-preserved\", \"conversion\": \"none\", \"platformVariant\": \"shared\", \"packageDestination\": \"Resources/content/${logical_path}\" }")
endforeach()
file(APPEND "${OUTPUT_FILE}" "\n  ]\n}\n")
