if(NOT DEFINED APP_BUNDLE OR NOT IS_DIRECTORY "${APP_BUNDLE}")
    message(FATAL_ERROR "APP_BUNDLE must identify a macOS application")
endif()
if(NOT DEFINED MAX_DEPLOYMENT_TARGET)
    message(FATAL_ERROR "MAX_DEPLOYMENT_TARGET is required")
endif()
file(REAL_PATH "${APP_BUNDLE}" APP_BUNDLE)

function(reject_local_paths file_path)
    file(READ "${file_path}" file_content)
    foreach(forbidden_prefix IN ITEMS
        "${SOURCE_ROOT}" "${BINARY_ROOT}" "/opt/homebrew/" "/Users/" "/Volumes/"
        "/var/folders/" "/private/var/folders/")
        if(NOT forbidden_prefix STREQUAL "")
            string(FIND "${file_content}" "${forbidden_prefix}" forbidden_index)
            if(NOT forbidden_index EQUAL -1)
                message(FATAL_ERROR
                    "Local path ${forbidden_prefix} is embedded in ${file_path}")
            endif()
        endif()
    endforeach()
endfunction()

execute_process(
    COMMAND /usr/bin/codesign --verify --deep --strict "${APP_BUNDLE}"
    RESULT_VARIABLE codesign_result
    ERROR_VARIABLE codesign_error)
if(NOT codesign_result EQUAL 0)
    message(FATAL_ERROR "Bundle signature verification failed: ${codesign_error}")
endif()

file(GLOB_RECURSE bundle_items LIST_DIRECTORIES false "${APP_BUNDLE}/Contents/*")
foreach(item IN LISTS bundle_items)
    get_filename_component(item_name "${item}" NAME)
    string(TOLOWER "${item_name}" item_name_lower)
    if(item_name_lower MATCHES "^fmod.*\\.(dylib|so|dll)$" OR
       item_name_lower MATCHES "^libfmod")
        message(FATAL_ERROR "Forbidden FMOD package file: ${item}")
    endif()
    if(IS_SYMLINK "${item}")
        file(READ_SYMLINK "${item}" link_target)
        if(IS_ABSOLUTE "${link_target}")
            message(FATAL_ERROR "Absolute bundle symlink: ${item} -> ${link_target}")
        endif()
        file(REAL_PATH "${item}" resolved_link)
        string(FIND "${resolved_link}" "${APP_BUNDLE}/" resolved_prefix)
        if(NOT resolved_prefix EQUAL 0 OR NOT EXISTS "${resolved_link}")
            message(FATAL_ERROR "Invalid bundle symlink: ${item} -> ${link_target}")
        endif()
        continue()
    endif()

    execute_process(COMMAND /usr/bin/file -b "${item}"
        OUTPUT_VARIABLE file_type OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(REJECT_LOCAL_PATHS AND
       file_type MATCHES "(text|script|source|XML|JSON|HTML|ASCII|Unicode|UTF-8)")
        reject_local_paths("${item}")
    endif()
    if(NOT file_type MATCHES "Mach-O")
        continue()
    endif()

    execute_process(COMMAND /usr/bin/strings -a "${item}"
        RESULT_VARIABLE strings_result OUTPUT_VARIABLE binary_strings)
    if(NOT strings_result EQUAL 0)
        message(FATAL_ERROR "strings failed for ${item}")
    endif()
    if(binary_strings MATCHES "FMOD::|FMOD_[A-Za-z0-9_]+|fmod(_vc|L)?\\.(dll|dylib|so)")
        message(FATAL_ERROR "Forbidden FMOD reference in ${item}")
    endif()
    execute_process(COMMAND /usr/bin/nm -u "${item}"
        RESULT_VARIABLE nm_result OUTPUT_VARIABLE undefined_symbols
        ERROR_QUIET)
    if((nm_result EQUAL 0 OR nm_result EQUAL 1) AND
       undefined_symbols MATCHES "_FMOD_|__ZN4FMOD")
        message(FATAL_ERROR "Forbidden FMOD symbol in ${item}")
    endif()

    execute_process(COMMAND /usr/bin/otool -L "${item}"
        RESULT_VARIABLE otool_result OUTPUT_VARIABLE dependencies)
    if(NOT otool_result EQUAL 0)
        message(FATAL_ERROR "otool failed for ${item}")
    endif()
    string(REPLACE "\n" ";" dependency_lines "${dependencies}")
    list(REMOVE_AT dependency_lines 0)
    foreach(dependency_line IN LISTS dependency_lines)
        string(STRIP "${dependency_line}" dependency_line)
        if(dependency_line STREQUAL "")
            continue()
        endif()
        string(REGEX MATCH "^[^ ]+" dependency "${dependency_line}")
        if(dependency MATCHES "^@rpath/(.+)$")
            get_filename_component(dependency_name "${dependency}" NAME)
            if(NOT EXISTS "${APP_BUNDLE}/Contents/Frameworks/${dependency_name}")
                message(FATAL_ERROR "Unresolved bundle dependency in ${item}: ${dependency}")
            endif()
        elseif(dependency MATCHES "^@executable_path/../Frameworks/(.+)$")
            if(NOT EXISTS "${APP_BUNDLE}/Contents/Frameworks/${CMAKE_MATCH_1}")
                message(FATAL_ERROR "Unresolved executable dependency in ${item}: ${dependency}")
            endif()
        elseif(dependency MATCHES "^@loader_path/(.+)$")
            get_filename_component(item_directory "${item}" DIRECTORY)
            file(REAL_PATH "${item_directory}/${CMAKE_MATCH_1}" resolved_dependency)
            string(FIND "${resolved_dependency}" "${APP_BUNDLE}/" dependency_prefix)
            if(NOT dependency_prefix EQUAL 0 OR NOT EXISTS "${resolved_dependency}")
                message(FATAL_ERROR "Invalid loader dependency in ${item}: ${dependency}")
            endif()
        elseif(NOT dependency MATCHES "^(/usr/lib/|/System/Library/)")
            message(FATAL_ERROR "Forbidden dependency in ${item}: ${dependency}")
        endif()
    endforeach()

    execute_process(COMMAND /usr/bin/otool -l "${item}"
        RESULT_VARIABLE load_commands_result OUTPUT_VARIABLE load_commands)
    if(NOT load_commands_result EQUAL 0)
        message(FATAL_ERROR "otool load-command scan failed for ${item}")
    endif()
    string(REPLACE "\n" ";" load_command_lines "${load_commands}")
    set(expect_rpath false)
    foreach(load_command_line IN LISTS load_command_lines)
        string(STRIP "${load_command_line}" load_command_line)
        if(load_command_line STREQUAL "cmd LC_RPATH")
            set(expect_rpath true)
        elseif(expect_rpath AND load_command_line MATCHES "^path ([^ ]+)")
            set(rpath "${CMAKE_MATCH_1}")
            if(NOT rpath MATCHES "^(@executable_path/|@loader_path/|/usr/lib/|/System/Library/)")
                message(FATAL_ERROR "Forbidden LC_RPATH in ${item}: ${rpath}")
            endif()
            set(expect_rpath false)
        endif()
    endforeach()

    execute_process(COMMAND /usr/bin/vtool -show-build "${item}"
        RESULT_VARIABLE vtool_result OUTPUT_VARIABLE build_versions)
    if(NOT vtool_result EQUAL 0)
        message(FATAL_ERROR "vtool failed for ${item}")
    endif()
    string(REGEX MATCH "minos[ \t]+([0-9]+(\\.[0-9]+)*)" minos_match
        "${build_versions}")
    if(NOT minos_match)
        message(FATAL_ERROR "No deployment target in ${item}")
    endif()
    set(minos "${CMAKE_MATCH_1}")
    if(minos VERSION_GREATER MAX_DEPLOYMENT_TARGET)
        message(FATAL_ERROR
            "${item} requires macOS ${minos}, expected at most ${MAX_DEPLOYMENT_TARGET}")
    endif()

    if(REJECT_LOCAL_PATHS)
        foreach(forbidden_prefix IN ITEMS
            "${SOURCE_ROOT}" "${BINARY_ROOT}" "/opt/homebrew/" "/Users/" "/Volumes/"
            "/var/folders/" "/private/var/folders/")
            if(NOT forbidden_prefix STREQUAL "")
                string(FIND "${binary_strings}" "${forbidden_prefix}" forbidden_index)
                if(NOT forbidden_index EQUAL -1)
                    message(FATAL_ERROR
                        "Local path ${forbidden_prefix} is embedded in ${item}")
                endif()
            endif()
        endforeach()
    endif()
endforeach()
